name: Run Python Hello World

on:
  push:
    branches:
      - main

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check Python version
        run: python --version

      - name: Run hello_world.py
        run: python hello_world.py
