name: Run new Program

on:
  push:
    branches:
      - main

jobs:
  run-greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run greet.py
        run: python python.py
