name: simple program to run

on:
  push:
    branches:
      - main

jobs:
  run-program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: run python.py
        run: python python.py
